services:
  bazarr-backend:
    build:
      context: ..
      dockerfile: dev-setup/Dockerfile.backend
    container_name: bazarr-backend
    ports:
      - "6767:6767"  # Bazarr backend API
    volumes:
      # Mount source code for live editing
      - ../bazarr:/app/bazarr/bin/bazarr:ro
      - ../custom_libs:/app/bazarr/bin/custom_libs:ro
      - ../libs:/app/bazarr/bin/libs:ro
      
      # Mount data directory for persistence
      - ./data:/app/bazarr/data
    environment:
      - SZ_USER_AGENT=bazarr-dev
      - BAZARR_VERSION=dev
      - PYTHONPATH=/app/bazarr/bin/custom_libs:/app/bazarr/bin/libs:/app/bazarr/bin/bazarr:/app/bazarr/bin
    restart: unless-stopped
    networks:
      - bazarr-network

  bazarr-frontend:
    build:
      context: ../frontend
      dockerfile: ../dev-setup/Dockerfile.frontend
    container_name: bazarr-frontend
    ports:
      - "5173:5173"  # Vite frontend dev server
    volumes:
      # Mount frontend source code for live editing
      - ../frontend/src:/app/src:ro
      - ../frontend/public:/app/public:ro
      - ../frontend/config:/app/config:ro
      - ../frontend/vite.config.ts:/app/vite.config.ts:ro
      - ../frontend/tsconfig.json:/app/tsconfig.json:ro
      - ../frontend/package.json:/app/package.json:ro
      - ../frontend/.env.development:/app/.env.development:ro
      
      # Ensure node_modules is not overwritten by volume mount
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_PROXY_URL=http://bazarr-backend:6767
      - VITE_BAZARR_CONFIG_FILE=/app/bazarr/data/config/config.yaml
      - VITE_CAN_UPDATE=true
      - VITE_HAS_UPDATE=false
      - VITE_REACT_QUERY_DEVTOOLS=true
    depends_on:
      - bazarr-backend
    restart: unless-stopped
    networks:
      - bazarr-network

networks:
  bazarr-network:
    driver: bridge

volumes:
  bazarr-dev-data:
    driver: local
